project:
  type: website
  output-dir: docs

website:
  title: "Sarah Dorny"
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/SDorny
      - icon: linkedin
        href: www.linkedin.com/in/sdorny
format:
  html:
    theme: cosmo
    css: styles.css



